### ISSUE TITLE
Emoji problems

### ISSUE THREAD

**Issue by guoyunhe** [dejavu-fonts/dejavu-fonts#333]
Today most operating systems support colored emoji fonts. In GNU/Linux, here is Noto ColorEmoji and Twemoji Color font. However, since Dejavu fonts covered a lot of emoji characters, they are shown as monochrome symbol.

For example, in Chromium open this page https://eosrei.github.io/emojione-color-font/full-demo.html

Some monochrome characters are still used. (mostly from Libration Sans, some from DejaVu Sans)

I read this page https://en.wikipedia.org/wiki/Emoticons_(Unicode_block)#Emoji which says that you can specify whether a font should use color emoji fonts or b/w symbol fonts. It does choose correct fonts for most emojis, but still some doesn't follow the rule.

**Comment by rellikmil** [comment]
Offtop: How make color fonts with FontForge?

**Comment by guoyunhe** [comment]
@den32ds no, you cannot. color fonts need special tools. and they are usually generated from SVG or PNG.

**Comment by rellikmil** [comment]
@guoyunhe Fontlab can make color fonts without special tools

**Comment by guoyunhe** [comment]
Closing this because the solution should be provided by applications, like Chrome/Firefox.
