### ISSUE TITLE
Import glyphs from GNU FreeFont

### ISSUE THREAD

**Issue by ghost** [dejavu-fonts/dejavu-fonts#361]
This can make DejaVu supporting more glyphs in more languages and improve the Hebrew Niqqud support.
Link to the official website of GNU FreeFont: [https://www.gnu.org/software/freefont/](https://www.gnu.org/software/freefont/)

**Comment by alerque** [comment]
Why? If GNU FreeFont supports what the character set / language you want to use, why not just use GNU FreeFont? I don't see the point in just copying glyphs around from other fonts if there isn't going to be any value added along the way.

**Comment by ghost** [comment]
The glyphs of Hebrew and Arabic are based on an older version of Noto Sans, and the newer version contains major improvements of the font (at least for Hebrew and Arabic). DejaVu font is used as a fallback font, and glyphs in Hebrew and Arabic look bad in the older version of Noto Sans. Updating the version of Noto Sans in DejaVu is not posibble because the licenses are not compatible, but GNU FreeFont license is compatible maybe. Also, importing glyphs from GNU FreeFont will increase the glyph support, this will be useful as DejaVu is used as a fallback font.

**Comment by fitojb** [comment]
I don’t know where you got that any glyph in DejaVu is based on Noto. When the DejaVu project started, it would be like a decade for the Noto project to be even announced

**Comment by fitojb** [comment]
Besides, the quality of non-Latin glyphs in FreeFont is very questionable

**Comment by ghost** [comment]
> Besides, the quality of non-Latin glyphs in FreeFont is very questionable

FreeFont is not as good as Noto Sans, but it contains glyphs of missing writing systems like Devanagari (see: https://github.com/dejavu-fonts/dejavu-fonts/issues/355), and GNU FreeFont and Noto fonts are the only fonts that support lots of languages (as I know).

**Comment by alerque** [comment]
I don't think you've offered a significant case why this would be an improvement. If the language coverage of GNU FreeFont suites your usage better, just use that. Mass importing a bunch of scripts from another font project is probably not a good match for this project at all and would break more people's current fallback arrangements than it fixes.

If there are specific problems with specific glyphs in existing range coverage lets hear what those issues are and also hear some specific comments on the design elements, why the glyphs you want to import are a good match, and what else it might affect (is existing content going to reflow?).

**Comment by ghost** [comment]
> I don't think you've offered a significant case why this would be an improvement. If the language coverage of GNU FreeFont suites your usage better, just use that. Mass importing a bunch of scripts from another font project is probably not a good match for this project at all and would break more people's current fallback arrangements than it fixes.
> 
> If there are specific problems with specific glyphs in existing range coverage lets hear what those issues are and also hear some specific comments on the design elements, why the glyphs you want to import are a good match, and what else it might affect (is existing content going to reflow?).

You are right, it is a very bad idea if it makes more problems than fixing. I'll close this issue.
