### ISSUE TITLE
DejaVu Sans Mono Superscript digits 4--9 are the wrong width.

### ISSUE THREAD

**Issue by jlturriff** [dejavu-fonts/dejavu-fonts#382]
The superscript digits (\u2074--\u2079) are narrower than the rest of the font, so in box diagrams they mangle the output (see attached image).
![DejaVu-Sans-Mono](https://user-images.githubusercontent.com/7597215/134855180-8eb76fb6-0784-4018-8a05-30925c01c9dc.png)

**Comment by kimmus** [comment]
Not obviously so. Subscript numbers, superscript numbers, regular numbers aligned:
![Numbers_cr](https://user-images.githubusercontent.com/60458875/135031759-33bf3f02-d93c-444a-97e7-e461cd0ee5f3.jpg)

**Comment by jlturriff** [comment]
I did a bit of research and I see that the issue is probably with the programs that are displaying the glyphs.  Presumably they are misinterpreting the fonts' metrics?
I attach more examples of what I'm seeing.  I've added some related glyphs as well; in particular, superscript i and n seem to be persistently narrower in all of the programs I've tried.
SuperSubScripts.txt is the text used in various programs to illustrate the issue.
SuperSubScripts*.png are images of the rendering of the text in various programs, where * is the name of each program.
![SuperSubScript-Gedit](https://user-images.githubusercontent.com/7597215/135177710-cbd6f5cb-c2bf-4d7a-b3cc-2a2cf22ca82b.png)
![SuperSubScript-Kate](https://user-images.githubusercontent.com/7597215/135177714-40a23f56-9051-4136-b68c-df19b9a6c997.png)
![SuperSubScript-Konsole](https://user-images.githubusercontent.com/7597215/135177716-01438226-cd29-481b-9a90-690c2242fcf4.png)
![SuperSubScript-Kwrite](https://user-images.githubusercontent.com/7597215/135177719-9e1ba72f-d9e7-4d1e-acb4-cc001c496432.png)
[SuperSubScripts.txt](https://github.com/dejavu-fonts/dejavu-fonts/files/7247760/SuperSubScripts.txt)

**Comment by jlturriff** [comment]
Huh.  Github isn't showing the names of the files.
The first one is Gedit (Gnome editor).
The second one is Kate (KDE Advanced Text Editor)
The third one is Konsole (KDE terminal emulator)
The fourth one is KWrite (another KDE text editor)
The last one is the text source file.

**Comment by kimmus** [comment]
The font doesn’t seem to be at fault. This is an export from LibreOffice Writer
![AllSubAndSuper_cr](https://user-images.githubusercontent.com/60458875/135218603-2579f900-9560-4d90-83a8-ae5093f8cecb.jpg)
:

**Comment by jlturriff** [comment]
Okay, thanks.  I'll take this up with my distro's maintainers.
