### ISSUE TITLE
Unicode characters not displayed in PDF

### ISSUE THREAD

**Issue by gretiere545** [dejavu-fonts/dejavu-fonts#384]
Hi,
I'm working on medical dictionnaries for migrants in different languages. 
I have issues with Pashto (Persian language with Arabic alphabet, like Farsi) and DejaVu Sans font. 
Some characters are replaced by a tofu square.

For instance : د کورنۍ په بل غړي باندې د بخار برید؟
is displayed with a _tofu square_ instead of ۍ (position 7 from the right)
This unicode character (ۍ) is U+FEF1 (ordinal 1741).

Language is Python 3 with FPDF library.

Thanks for your help.

Kind regards
Gilles

**Comment by kimmus** [comment]
The character you quote is actually U+06CD, which isn’t present in any of the DevuVu fonts. If that’s the character you intend to use, you need to use a different font.

**Comment by gretiere545** [comment]
Thank you ! You're right, this is actually U+06CD (https://unicode-table.com/en/search/?q=1741. )
I've got the same issue with U+FEF1.
As these characters are frequent in pashto, is there any chance to have them being added to the font ? 
Kind regards

**Comment by kimmus** [comment]
The DejaVu fonts are no longer maintained, so the chances of anything being added or fixed are slim.
