### ISSUE TITLE
make error: missing Block.txt in git repo

### ISSUE THREAD

**Issue by vtorri** [dejavu-fonts/dejavu-fonts#392]
i was trying to compile the project from git and I had that error:

Unable to open resources/Blocks.txt : No such file or directory

would it be possible to add that file ?

a solution to avoid these problems is to add github actions for CI (travis is not free anymore)

**Comment by eugmes** [comment]
The blocks file is available from Unicode. The newest version is here: https://unicode.org/Public/UNIDATA/Blocks.txt

**Comment by vtorri** [comment]
ok, closing
